### ISSUE TITLE
What is the difference between pai-torchacc and torchacc?

### ISSUE THREAD

**Issue by a1342772** [AlibabaPAI/torchacc#18]

**Comment by a1342772** [comment]
@anw90

**Comment by anw90** [comment]
pai-torchacc and torchacc are the same thing, developed by the PAI team at Alibaba Cloud.  You can try it out by visiting [flashmodels](https://github.com/AlibabaPAI/flashmodels) or review the documentation for [torchacc](https://torchacc.readthedocs.io/en/latest/).
